# Generated by Django 4.1.1 on 2022-11-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(null=True, to='product.size'),
        ),
    ]
