# Generated by Django 4.1.1 on 2022-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='products_id',
        ),
    ]
