# Generated by Django 4.1.1 on 2022-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(to='product.size'),
        ),
        migrations.RemoveField(
            model_name='product_version',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='product_version',
            name='size_id',
        ),
        migrations.AddField(
            model_name='product_version',
            name='color_id',
            field=models.ManyToManyField(to='product.color'),
        ),
        migrations.AddField(
            model_name='product_version',
            name='size_id',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
