# Generated by Django 4.1.1 on 2022-09-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_review_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='products_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
