# Generated by Django 4.1.1 on 2022-11-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='product_version',
            name='size_id',
        ),
        migrations.AddField(
            model_name='product_version',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='product.color'),
        ),
        migrations.AddField(
            model_name='product_version',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_id', to='product.size'),
        ),
    ]
