# Generated by Django 4.1.1 on 2022-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_version_color_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='size_id',
        ),
        migrations.AddField(
            model_name='product_version',
            name='size_id',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
