# Generated by Django 4.1.1 on 2022-10-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
