# Generated by Django 4.1.1 on 2022-11-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_version_size_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_version',
            name='discount_price',
            field=models.FloatField(max_length=250),
        ),
    ]
