# Generated by Django 4.1.1 on 2022-11-21 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_version_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_version',
            name='stocks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
