# Generated by Django 4.1.1 on 2022-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
