# Generated by Django 4.1.1 on 2022-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brands_id',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sizes',
            new_name='product_size',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(to='product.color'),
        ),
    ]
