# Generated by Django 4.1.1 on 2022-10-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_brands_id_product_brand_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(to='product.category'),
        ),
    ]
