# Generated by Django 4.1.1 on 2022-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_categories_az_category_categories_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(null=True, to='product.category'),
        ),
    ]
