# Generated by Django 4.1.1 on 2022-10-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_category_id_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
