# Generated by Django 4.1.1 on 2022-10-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='cover_image_version',
            field=models.ImageField(null=True, unique=True, upload_to='Cover_images_version'),
        ),
    ]
