# Generated by Django 4.1.1 on 2022-10-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_version_cover_image_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_version',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='product.color'),
        ),
        migrations.AlterField(
            model_name='product_version',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_id', to='product.size'),
        ),
    ]
