# Generated by Django 4.1.1 on 2022-11-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_size'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_items',
            new_name='Cart_item',
        ),
        migrations.RenameModel(
            old_name='Wishlists',
            new_name='Wishlist',
        ),
    ]
