# Generated by Django 4.1.1 on 2022-09-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_city_user_citys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='citys',
            new_name='city',
        ),
    ]
