# Generated by Django 4.1.1 on 2022-11-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_email_newsletter_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='emails',
            new_name='email',
        ),
    ]
