# Generated by Django 4.1.1 on 2022-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments_blog_od'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog_od',
            new_name='blog_id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
