# Generated by Django 4.1.1 on 2022-10-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items_id',
        ),
        migrations.AddField(
            model_name='cart_items',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
    ]
