# Generated by Django 4.1.1 on 2022-10-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_version_cover_image_version'),
        ('order', '0004_alter_cart_items_product_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='product_version_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_version_id', to='product.product_version'),
        ),
    ]
